### ISSUE TITLE
Model weights publication?

### ISSUE THREAD

**Issue by Sandspeare** [lmu-plai/xfl#2]
Hi all - thank you for the excellent work you have done on this paper - I am also doing research on function naming and trying to replicate your work, is it possible to get your model weights, there seems to be no model file under the lm/data/ path, and i don't know how to run the lm.py.

- have i miss anything?

**Comment by Ch3nYe** [comment]
the same question

**Comment by benoittrist** [comment]
Thank you for your interest, you may be interested by the new XFL refactoring and models [here]( https://doi.org/10.5281/zenodo.10733597) .
These weights are not the same as the one of the paper, but they are the one we make available.
